// ISO 3166-1 alpha-2 country code -> UN-geoscheme-style subregion.
// Sourced from the mledoze/countries public dataset. Used to auto-derive a
// location's subregion from its country code, so contributors never have to
// pick a UN-geoscheme label themselves.
const SUBREGION_BY_COUNTRY = {
  AD: "Southern Europe",
  AE: "Western Asia",
  AF: "Southern Asia",
  AG: "Caribbean",
  AI: "Caribbean",
  AL: "Southeast Europe",
  AM: "Western Asia",
  AO: "Middle Africa",
  AR: "South America",
  AS: "Polynesia",
  AT: "Central Europe",
  AU: "Australia and New Zealand",
  AW: "Caribbean",
  AX: "Northern Europe",
  AZ: "Western Asia",
  BA: "Southeast Europe",
  BB: "Caribbean",
  BD: "Southern Asia",
  BE: "Western Europe",
  BF: "Western Africa",
  BG: "Southeast Europe",
  BH: "Western Asia",
  BI: "Eastern Africa",
  BJ: "Western Africa",
  BL: "Caribbean",
  BM: "Northern America",
  BN: "South-Eastern Asia",
  BO: "South America",
  BQ: "Caribbean",
  BR: "South America",
  BS: "Caribbean",
  BT: "Southern Asia",
  BW: "Southern Africa",
  BY: "Eastern Europe",
  BZ: "Central America",
  CA: "Northern America",
  CC: "Australia and New Zealand",
  CD: "Middle Africa",
  CF: "Middle Africa",
  CG: "Middle Africa",
  CH: "Western Europe",
  CI: "Western Africa",
  CK: "Polynesia",
  CL: "South America",
  CM: "Middle Africa",
  CN: "Eastern Asia",
  CO: "South America",
  CR: "Central America",
  CU: "Caribbean",
  CV: "Western Africa",
  CW: "Caribbean",
  CX: "Australia and New Zealand",
  CY: "Southern Europe",
  CZ: "Central Europe",
  DE: "Western Europe",
  DJ: "Eastern Africa",
  DK: "Northern Europe",
  DM: "Caribbean",
  DO: "Caribbean",
  DZ: "Northern Africa",
  EC: "South America",
  EE: "Northern Europe",
  EG: "Northern Africa",
  EH: "Northern Africa",
  ER: "Eastern Africa",
  ES: "Southern Europe",
  ET: "Eastern Africa",
  FI: "Northern Europe",
  FJ: "Melanesia",
  FK: "South America",
  FM: "Micronesia",
  FO: "Northern Europe",
  FR: "Western Europe",
  GA: "Middle Africa",
  GB: "Northern Europe",
  GD: "Caribbean",
  GE: "Western Asia",
  GF: "South America",
  GG: "Northern Europe",
  GH: "Western Africa",
  GI: "Southern Europe",
  GL: "Northern America",
  GM: "Western Africa",
  GN: "Western Africa",
  GP: "Caribbean",
  GQ: "Middle Africa",
  GR: "Southern Europe",
  GT: "Central America",
  GU: "Micronesia",
  GW: "Western Africa",
  GY: "South America",
  HK: "Eastern Asia",
  HN: "Central America",
  HR: "Southeast Europe",
  HT: "Caribbean",
  HU: "Central Europe",
  ID: "South-Eastern Asia",
  IE: "Northern Europe",
  IL: "Western Asia",
  IM: "Northern Europe",
  IN: "Southern Asia",
  IO: "Eastern Africa",
  IQ: "Western Asia",
  IR: "Southern Asia",
  IS: "Northern Europe",
  IT: "Southern Europe",
  JE: "Northern Europe",
  JM: "Caribbean",
  JO: "Western Asia",
  JP: "Eastern Asia",
  KE: "Eastern Africa",
  KG: "Central Asia",
  KH: "South-Eastern Asia",
  KI: "Micronesia",
  KM: "Eastern Africa",
  KN: "Caribbean",
  KP: "Eastern Asia",
  KR: "Eastern Asia",
  KW: "Western Asia",
  KY: "Caribbean",
  KZ: "Central Asia",
  LA: "South-Eastern Asia",
  LB: "Western Asia",
  LC: "Caribbean",
  LI: "Western Europe",
  LK: "Southern Asia",
  LR: "Western Africa",
  LS: "Southern Africa",
  LT: "Northern Europe",
  LU: "Western Europe",
  LV: "Northern Europe",
  LY: "Northern Africa",
  MA: "Northern Africa",
  MC: "Western Europe",
  MD: "Eastern Europe",
  ME: "Southeast Europe",
  MF: "Caribbean",
  MG: "Eastern Africa",
  MH: "Micronesia",
  MK: "Southeast Europe",
  ML: "Western Africa",
  MM: "South-Eastern Asia",
  MN: "Eastern Asia",
  MO: "Eastern Asia",
  MP: "Micronesia",
  MQ: "Caribbean",
  MR: "Western Africa",
  MS: "Caribbean",
  MT: "Southern Europe",
  MU: "Eastern Africa",
  MV: "Southern Asia",
  MW: "Eastern Africa",
  MX: "Central America",
  MY: "South-Eastern Asia",
  MZ: "Eastern Africa",
  NA: "Southern Africa",
  NC: "Melanesia",
  NE: "Western Africa",
  NF: "Australia and New Zealand",
  NG: "Western Africa",
  NI: "Central America",
  NL: "Western Europe",
  NO: "Northern Europe",
  NP: "Southern Asia",
  NR: "Micronesia",
  NU: "Polynesia",
  NZ: "Australia and New Zealand",
  OM: "Western Asia",
  PA: "Central America",
  PE: "South America",
  PF: "Polynesia",
  PG: "Melanesia",
  PH: "South-Eastern Asia",
  PK: "Southern Asia",
  PL: "Central Europe",
  PM: "Northern America",
  PN: "Polynesia",
  PR: "Caribbean",
  PS: "Western Asia",
  PT: "Southern Europe",
  PW: "Micronesia",
  PY: "South America",
  QA: "Western Asia",
  RE: "Eastern Africa",
  RO: "Southeast Europe",
  RS: "Southeast Europe",
  RU: "Eastern Europe",
  RW: "Eastern Africa",
  SA: "Western Asia",
  SB: "Melanesia",
  SC: "Eastern Africa",
  SD: "Northern Africa",
  SE: "Northern Europe",
  SG: "South-Eastern Asia",
  SH: "Western Africa",
  SI: "Central Europe",
  SJ: "Northern Europe",
  SK: "Central Europe",
  SL: "Western Africa",
  SM: "Southern Europe",
  SN: "Western Africa",
  SO: "Eastern Africa",
  SR: "South America",
  SS: "Middle Africa",
  ST: "Middle Africa",
  SV: "Central America",
  SX: "Caribbean",
  SY: "Western Asia",
  SZ: "Southern Africa",
  TC: "Caribbean",
  TD: "Middle Africa",
  TG: "Western Africa",
  TH: "South-Eastern Asia",
  TJ: "Central Asia",
  TK: "Polynesia",
  TL: "South-Eastern Asia",
  TM: "Central Asia",
  TN: "Northern Africa",
  TO: "Polynesia",
  TR: "Western Asia",
  TT: "Caribbean",
  TV: "Polynesia",
  TW: "Eastern Asia",
  TZ: "Eastern Africa",
  UA: "Eastern Europe",
  UG: "Eastern Africa",
  UM: "Northern America",
  US: "Northern America",
  UY: "South America",
  UZ: "Central Asia",
  VA: "Southern Europe",
  VC: "Caribbean",
  VE: "South America",
  VG: "Caribbean",
  VI: "Caribbean",
  VN: "South-Eastern Asia",
  VU: "Melanesia",
  WF: "Polynesia",
  WS: "Polynesia",
  XK: "Southeast Europe",
  YE: "Western Asia",
  YT: "Eastern Africa",
  ZA: "Southern Africa",
  ZM: "Eastern Africa",
  ZW: "Eastern Africa",
};

// Region is a pure function of subregion, so it is derived rather than asked
// for — a contributor knows their country, not which UN geoscheme bucket it
// sits in. Every value in SUBREGION_BY_COUNTRY must appear here.
const REGION_BY_SUBREGION = {
  "Australia and New Zealand": "Oceania",
  Melanesia: "Oceania",
  Micronesia: "Oceania",
  Polynesia: "Oceania",
  Caribbean: "Americas",
  "Central America": "Americas",
  "Northern America": "Americas",
  "South America": "Americas",
  "Central Asia": "Asia",
  "Eastern Asia": "Asia",
  "South-Eastern Asia": "Asia",
  "Southern Asia": "Asia",
  "Western Asia": "Asia",
  "Central Europe": "Europe",
  "Eastern Europe": "Europe",
  "Northern Europe": "Europe",
  "Southeast Europe": "Europe",
  "Southern Europe": "Europe",
  "Western Europe": "Europe",
  "Eastern Africa": "Africa",
  "Middle Africa": "Africa",
  "Northern Africa": "Africa",
  "Southern Africa": "Africa",
  "Western Africa": "Africa",
};

function subregionFor(countryCode) {
  return SUBREGION_BY_COUNTRY[String(countryCode || "").toUpperCase()] || "";
}

function regionFor(countryCode) {
  return REGION_BY_SUBREGION[subregionFor(countryCode)] || "";
}

module.exports = { SUBREGION_BY_COUNTRY, REGION_BY_SUBREGION, subregionFor, regionFor };
